// TEMPORARY DATA

export let role = "patient";

export const doctorsData = [
  {
    id: 1,
    doctorId: "1234567890",
    name: "Tran Quoc An",
    email: "tqan@gmail.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    specialties: ["Heart Failure Management", "Geometry"],
    departments: ["1B", "NEUROLOGY", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    doctorId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    specialties: ["Dermatology", "Gastroenterologist"],
    departments: ["Emergency Medicine"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    doctorId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    specialties: ["Immunologist","Cardiology"],
    departments: ["Emergency Medicine", "Internal Medicine", "Pediatrics"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    doctorId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    specialties: ["Cardiology"],
    departments: ["Pediatrics", "Gynecology (OB/GYN)"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    doctorId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    specialties: ["Cardiology"],
    departments: ["Pulmonology", "Emergency Medicine", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    doctorId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    specialties: ["Cardiology","Dermatology"],
    departments: ["Critical Care", "Pulmonology"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    doctorId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    specialties: ["Dermatology", "Pediatrics"],
    departments: ["GASTROENTEROLOGY", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    doctorId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    specialties: ["Allergist / Immunologist", "Endocrinologist"],
    departments: ["GASTROENTEROLOGY", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    doctorId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    specialties: ["Dermatologist", "Cardiology"],
    departments: ["GASTROENTEROLOGY", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    doctorId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    specialties: ["Cardiology"],
    departments: ["GASTROENTEROLOGY", "4B", "3C"],
    address: "123 Main St, Anytown, USA",
  },
];

export const patientsData = [
  {
    id: 1,
    patientId: "1234567890",
    name: "John Doe",
    email: "john@doe.com",
    photo:
      "https://images.pexels.com/photos/2888150/pexels-photo-2888150.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    areas: 5,
    department: "1B",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    patientId: "1234567890",
    name: "Jane Doe",
    email: "jane@doe.com",
    photo:
      "https://images.pexels.com/photos/936126/pexels-photo-936126.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    areas: 5,
    department: "GASTROENTEROLOGY",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    patientId: "1234567890",
    name: "Mike Geller",
    email: "mike@geller.com",
    photo:
      "https://images.pexels.com/photos/428328/pexels-photo-428328.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    areas: 5,
    department: "GASTROENTEROLOGY",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    patientId: "1234567890",
    name: "Jay French",
    email: "jay@gmail.com",
    photo:
      "https://images.pexels.com/photos/1187765/pexels-photo-1187765.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    areas: 5,
    department: "GASTROENTEROLOGY",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    patientId: "1234567890",
    name: "Jane Smith",
    email: "jane@gmail.com",
    photo:
      "https://images.pexels.com/photos/1102341/pexels-photo-1102341.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    areas: 5,
    department: "GASTROENTEROLOGY",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    patientId: "1234567890",
    name: "Anna Santiago",
    email: "anna@gmail.com",
    photo:
      "https://images.pexels.com/photos/712513/pexels-photo-712513.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    areas: 5,
    department: "GASTROENTEROLOGY",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    patientId: "1234567890",
    name: "Allen Black",
    email: "allen@black.com",
    photo:
      "https://images.pexels.com/photos/1438081/pexels-photo-1438081.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    areas: 5,
    department: "GASTROENTEROLOGY",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    patientId: "1234567890",
    name: "Ophelia Castro",
    email: "ophelia@castro.com",
    photo:
      "https://images.pexels.com/photos/1036623/pexels-photo-1036623.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    areas: 5,
    department: "GASTROENTEROLOGY",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    patientId: "1234567890",
    name: "Derek Briggs",
    email: "derek@briggs.com",
    photo:
      "https://images.pexels.com/photos/842980/pexels-photo-842980.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    areas: 5,
    department: "GASTROENTEROLOGY",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    patientId: "1234567890",
    name: "John Glover",
    email: "john@glover.com",
    photo:
      "https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=1200",
    phone: "1234567890",
    areas: 5,
    department: "GASTROENTEROLOGY",
    address: "123 Main St, Anytown, USA",
  },
];

export const parentsData = [
  {
    id: 1,
    name: "John Doe",
    patients: ["Sarah Brewer"],
    email: "john@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 2,
    name: "Jane Doe",
    patients: ["Cecilia Bradley"],
    email: "jane@doe.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 3,
    name: "Mike Geller",
    patients: ["Fanny Caldwell"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 4,
    name: "Jay French",
    patients: ["Mollie Fitzgerald", "Ian Bryant"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 5,
    name: "Jane Smith",
    patients: ["Mable Harvey"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 6,
    name: "Anna Santiago",
    patients: ["Joel Lambert"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 7,
    name: "Allen Black",
    patients: ["Carrie Tucker", "Lilly Underwood"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 8,
    name: "Ophelia Castro",
    patients: ["Alexander Blair"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 9,
    name: "Derek Briggs",
    patients: ["Susan Webster", "Maude Stone"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
  {
    id: 10,
    name: "John Glover",
    patients: ["Stella Scott"],
    email: "mike@geller.com",
    phone: "1234567890",
    address: "123 Main St, Anytown, USA",
  },
];

export const specialtiesData = [
  {
    id: 1,
    name: "Heart Failure Management",
    doctors: ["Alice Phelps", "Russell Davidson"],
  },
  {
    id: 2,
    name: "Electrophysiology",
    doctors: ["Manuel Becker", "Eddie Chavez"],
  },
  {
    id: 3,
    name: "Stroke Management",
    doctors: ["Lola Newman", "Darrell Delgado"],
  },
  {
    id: 4,
    name: "Neonatology",
    doctors: ["Nathan Kelly", "Benjamin Snyder"],
  },
  {
    id: 5,
    name: "Movement Disorders",
    doctors: ["Alma Benson", "Lina Collier"],
  },
  {
    id: 6,
    name: "Medical Oncology",
    doctors: ["Hannah Bowman", "Betty Obrien"],
  },
  {
    id: 7,
    name: "Surgical Oncology",
    doctors: ["Lora French", "Sue Brady"],
  },
  {
    id: 8,
    name: "Radiation Oncology",
    doctors: ["Harriet Alvarado", "Mayme Keller"],
  },
  {
    id: 9,
    name: "Radiation Oncology",
    doctors: ["Gertrude Roy", "Rosa Singleton"],
  },
  {
    id: 10,
    name: "Radiation Oncology",
    doctors: ["Effie Lynch", "Brett Flowers"],
  },
];

export const departmentsData = [
  {
    id: 1,
    name: "Cardiology",
    capacity: 20,
    areas: 1,
    supervisor: "Joseph Padilla",
  },
  {
    id: 2,
    name: "Neurology",
    capacity: 22,
    areas: 2,
    supervisor: "Blake Joseph",
  },
  {
    id: 3,
    name: "Oncology",
    capacity: 20,
    areas: 3,
    supervisor: "Tom Bennett",
  },
  {
    id: 4,
    name: "Pediatrics",
    capacity: 18,
    areas: 4,
    supervisor: "Aaron Collins",
  },
  {
    id: 5,
    name: "Gastroenterology",
    capacity: 16,
    areas: 5,
    supervisor: "Iva Frank",
  },
  {
    id: 5,
    name: "Vascular Surgeon",
    capacity: 20,
    areas: 5,
    supervisor: "Leila Santos",
  },
  {
    id: 7,
    name: "Emergency Medicine",
    capacity: 18,
    areas: 7,
    supervisor: "Carrie Walton",
  },
  {
    id: 8,
    name: "Radiology",
    capacity: 22,
    areas: 6,
    supervisor: "Christopher Butler",
  },
  {
    id: 9,
    name: "Pharmacist",
    capacity: 18,
    areas: 6,
    supervisor: "Marc Miller",
  },
  {
    id: 10,
    name: "Armetric",
    capacity: 20,
    areas: 6,
    supervisor: "Ophelia Marsh",
  },
];

export const medicalsData = [
  {
    id: 1,
    specialty: "Heart Failure Management",
    department: "Cardiology",
    doctor: "Tommy Wise",
  },
  {
    id: 2,
    specialty: "Electrophysiology",
    department: "Neurology",
    doctor: "Rhoda Frank",
  },
  {
    id: 3,
    specialty: "Stroke Management",
    department: "Oncology",
    doctor: "Della Dunn",
  },
  {
    id: 4,
    specialty: "Epilepsy",
    department: "Pediatrics",
    doctor: "Bruce Rodriguez",
  },
  {
    id: 5,
    specialty: "Epilepsy",
    department: "Gastroenterology",
    doctor: "Birdie Butler",
  },
  {
    id: 6,
    specialty: "Movement Disorders",
    department: "Vascular Surgeon",
    doctor: "Bettie Oliver",
  },
  {
    id: 7,
    specialty: "Medical Oncology",
    department: "Emergency Medicine",
    doctor: "Herman Howard",
  },
  {
    id: 8,
    specialty: "Radiation Oncology",
    department: "Radiology",
    doctor: "Lucinda Thomas",
  },
  {
    id: 9,
    specialty: "Radiation Oncology",
    department: "Pharmacist",
    doctor: "Ronald Roberts",
  },
  {
    id: 10,
    specialty: "Neonatology",
    department: "Armetric",
    doctor: "Julia Pittman",
  },
];

export const medicaldescriptionsData = [
  {
    id: 1,
    specialty: "Heart Failure Management",
    department: "CARDIOLOGY",
    doctor: "Martha Morris",
    date: "2025-01-01",
  },
  {
    id: 2,
    specialty: "Electrophysiology",
    department: "NEUROLOGY",
    doctor: "Randall Garcia",
    date: "2025-01-01",
  },
  {
    id: 3,
    specialty: "Stroke Management",
    department: "ONCOLOGY",
    doctor: "Myrtie Scott",
    date: "2025-01-01",
  },
  {
    id: 4,
    specialty: "Movement Disorders",
    department: "1B",
    doctor: "Alvin Swanson",
    date: "2025-01-01",
  },
  {
    id: 5,
    specialty: "Medical Oncology",
    department: "PEDIATRICS",
    doctor: "Mabelle Wallace",
    date: "2025-01-01",
  },
  {
    id: 6,
    specialty: "Surgical Oncology",
    department: "GASTROENTEROLOGY",
    doctor: "Dale Thompson",
    date: "2025-01-01",
  },
  {
    id: 7,
    specialty: "Surgical Oncology",
    department: "VASCULAR SURGEON",
    doctor: "Allie Conner",
    date: "2025-01-01",
  },
  {
    id: 8,
    specialty: "Geography",
    department: "6B",
    doctor: "Hunter Fuller",
    date: "2025-01-01",
  },
  {
    id: 9,
    specialty: "Radiation Oncology",
    department: "EMERGENCY MEDICINE",
    doctor: "Lois Lindsey",
    date: "2025-01-01",
  },
  {
    id: 10,
    specialty: "Radiation Oncology",
    department: "RADIOLOGY",
    doctor: "Vera Soto",
    date: "2025-01-01",
  },
];

export const assignmentsData = [
  {
    id: 1,
    specialty: "Heart Failure Management",
    department: "CARDIOLOGY",
    doctor: "Anthony Boone",
    dueDate: "2025-01-01",
  },
  {
    id: 2,
    specialty: "Electrophysiology",
    department: "NEUROLOGY",
    doctor: "Clifford Bowen",
    dueDate: "2025-01-01",
  },
  {
    id: 3,
    specialty: "Stroke Management",
    department: "ONCOLOGY",
    doctor: "Catherine Malone",
    dueDate: "2025-01-01",
  },
  {
    id: 4,
    specialty: "Movement Disorders",
    department: "1B",
    doctor: "Willie Medina",
    dueDate: "2025-01-01",
  },
  {
    id: 5,
    specialty: "Medical Oncology",
    department: "PEDIATRICS",
    doctor: "Jose Ruiz",
    dueDate: "2025-01-01",
  },
  {
    id: 6,
    specialty: "Surgical Oncology",
    department: "GASTROENTEROLOGY",
    doctor: "Katharine Owens",
    dueDate: "2025-01-01",
  },
  {
    id: 7,
    specialty: "Surgical Oncology",
    department: "VASCULAR SURGEON",
    doctor: "Shawn Norman",
    dueDate: "2025-01-01",
  },
  {
    id: 8,
    specialty: "Geography",
    department: "6B",
    doctor: "Don Holloway",
    dueDate: "2025-01-01",
  },
  {
    id: 9,
    specialty: "Radiation Oncology",
    department: "EMERGENCY MEDICINE",
    doctor: "Franklin Gregory",
    dueDate: "2025-01-01",
  },
  {
    id: 10,
    specialty: "Radiation Oncology",
    department: "RADIOLOGY",
    doctor: "Danny Nguyen",
    dueDate: "2025-01-01",
  },
];

export const medicalprescriptionsData = [
  {
    id: 1,
    specialty: "Heart Failure Management",
    department: "CARDIOLOGY",
    doctor: "John Doe",
    patient: "John Doe",
    date: "2025-01-01",
    type: "medicaldescription",
    score: 90,
  },
  {
    id: 2,
    specialty: "Electrophysiology",
    department: "NEUROLOGY",
    doctor: "John Doe",
    patient: "John Doe",
    date: "2025-01-01",
    type: "medicaldescription",
    score: 90,
  },
  {
    id: 3,
    specialty: "Stroke Management",
    department: "ONCOLOGY",
    doctor: "John Doe",
    patient: "John Doe",
    date: "2025-01-01",
    type: "medicaldescription",
    score: 90,
  },
  {
    id: 4,
    specialty: "Movement Disorders",
    department: "1B",
    doctor: "John Doe",
    patient: "John Doe",
    date: "2025-01-01",
    type: "medicaldescription",
    score: 90,
  },
  {
    id: 5,
    specialty: "Medical Oncology",
    department: "PEDIATRICS",
    doctor: "John Doe",
    patient: "John Doe",
    date: "2025-01-01",
    type: "medicaldescription",
    score: 90,
  },
  {
    id: 6,
    specialty: "Surgical Oncology",
    department: "GASTROENTEROLOGY",
    doctor: "John Doe",
    patient: "John Doe",
    date: "2025-01-01",
    type: "medicaldescription",
    score: 90,
  },
  {
    id: 7,
    specialty: "Surgical Oncology",
    department: "VASCULAR SURGEON",
    doctor: "John Doe",
    patient: "John Doe",
    date: "2025-01-01",
    type: "medicaldescription",
    score: 90,
  },
  {
    id: 8,
    specialty: "Geography",
    department: "6B",
    doctor: "John Doe",
    patient: "John Doe",
    date: "2025-01-01",
    type: "medicaldescription",
    score: 90,
  },
  {
    id: 9,
    specialty: "Radiation Oncology",
    department: "EMERGENCY MEDICINE",
    doctor: "John Doe",
    patient: "John Doe",
    date: "2025-01-01",
    type: "medicaldescription",
    score: 90,
  },
  {
    id: 10,
    specialty: "Radiation Oncology",
    department: "RADIOLOGY",
    doctor: "John Doe",
    patient: "John Doe",
    date: "2025-01-01",
    type: "medicaldescription",
    score: 90,
  },
];

export const eventsData = [
  {
    id: 1,
    title: "Lake Trip",
    department: "CARDIOLOGY",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 2,
    title: "Picnic",
    department: "NEUROLOGY",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 3,
    title: "Beach Trip",
    department: "ONCOLOGY",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 4,
    title: "Museum Trip",
    department: "PEDIATRICS",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 5,
    title: "Surgical Oncology Concert",
    department: "GASTROENTEROLOGY",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 6,
    title: "Magician Show",
    department: "1B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 7,
    title: "Lake Trip",
    department: "2B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 8,
    title: "Cycling Race",
    department: "3B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 9,
    title: "Medical Oncology Exhibition",
    department: "4B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
  {
    id: 10,
    title: "Sports Tournament",
    department: "5B",
    date: "2025-01-01",
    startTime: "10:00",
    endTime: "11:00",
  },
];

export const announcementsData = [
  {
    id: 1,
    title: "About PEDIATRICS Heart Failure Management Test",
    department: "PEDIATRICS",
    date: "2025-01-01",
  },
  {
    id: 2,
    title: "About ONCOLOGY Heart Failure Management Test",
    department: "ONCOLOGY",
    date: "2025-01-01",
  },
  {
    id: 3,
    title: "About 3B Heart Failure Management Test",
    department: "3B",
    date: "2025-01-01",
  },
  {
    id: 4,
    title: "About VASCULAR SURGEON Heart Failure Management Test",
    department: "VASCULAR SURGEON",
    date: "2025-01-01",
  },
  {
    id: 5,
    title: "About 8C Heart Failure Management Test",
    department: "8C",
    date: "2025-01-01",
  },
  {
    id: 6,
    title: "About NEUROLOGY Heart Failure Management Test",
    department: "NEUROLOGY",
    date: "2025-01-01",
  },
  {
    id: 7,
    title: "About 4C Heart Failure Management Test",
    department: "4C",
    date: "2025-01-01",
  },
  {
    id: 8,
    title: "About 4B Heart Failure Management Test",
    department: "4B",
    date: "2025-01-01",
  },
  {
    id: 9,
    title: "About 3C Heart Failure Management Test",
    department: "3C",
    date: "2025-01-01",
  },
  {
    id: 10,
    title: "About 1C Heart Failure Management Test",
    department: "1C",
    date: "2025-01-01",
  },
];


// YOU SHOULD CHANGE THE DATES OF THE EVENTS TO THE CURRENT DATE TO SEE THE EVENTS ON THE CALENDAR
export const calendarEvents = [
  {
    title: "Heart Failure Management",
    allDay: false,
    start: new Date(2024, 7, 12, 8, 0),
    end: new Date(2024, 7, 12, 8, 45),
  },
  {
    title: "Electrophysiology",
    allDay: false,
    start: new Date(2024, 7, 12, 9, 0),
    end: new Date(2024, 7, 12, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 12, 10, 0),
    end: new Date(2024, 7, 12, 10, 45),
  },
  {
    title: "Radiation Oncology",
    allDay: false,
    start: new Date(2024, 7, 12, 11, 0),
    end: new Date(2024, 7, 12, 11, 45),
  },
  {
    title: "Radiation Oncology",
    allDay: false,
    start: new Date(2024, 7, 12, 13, 0),
    end: new Date(2024, 7, 12, 13, 45),
  },
  {
    title: "Surgical Oncology",
    allDay: false,
    start: new Date(2024, 7, 12, 14, 0),
    end: new Date(2024, 7, 12, 14, 45),
  },
  {
    title: "Electrophysiology",
    allDay: false,
    start: new Date(2024, 7, 13, 9, 0),
    end: new Date(2024, 7, 13, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 13, 10, 0),
    end: new Date(2024, 7, 13, 10, 45),
  },
  {
    title: "Radiation Oncology",
    allDay: false,
    start: new Date(2024, 7, 13, 11, 0),
    end: new Date(2024, 7, 13, 11, 45),
  },

  {
    title: "Surgical Oncology",
    allDay: false,
    start: new Date(2024, 7, 13, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "Heart Failure Management",
    allDay: false,
    start: new Date(2024, 7, 14, 8, 0),
    end: new Date(2024, 7, 14, 8, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 14, 10, 0),
    end: new Date(2024, 7, 14, 10, 45),
  },

  {
    title: "Radiation Oncology",
    allDay: false,
    start: new Date(2024, 7, 14, 13, 0),
    end: new Date(2024, 7, 14, 13, 45),
  },
  {
    title: "Surgical Oncology",
    allDay: false,
    start: new Date(2024, 7, 14, 14, 0),
    end: new Date(2024, 7, 13, 14, 45),
  },
  {
    title: "Electrophysiology",
    allDay: false,
    start: new Date(2024, 7, 15, 9, 0),
    end: new Date(2024, 7, 15, 9, 45),
  },
  {
    title: "Biology",
    allDay: false,
    start: new Date(2024, 7, 15, 10, 0),
    end: new Date(2024, 7, 15, 10, 45),
  },
  {
    title: "Radiation Oncology",
    allDay: false,
    start: new Date(2024, 7, 15, 11, 0),
    end: new Date(2024, 7, 15, 11, 45),
  },

  {
    title: "Surgical Oncology",
    allDay: false,
    start: new Date(2024, 7, 15, 14, 0),
    end: new Date(2024, 7, 15, 14, 45),
  },
  {
    title: "Heart Failure Management",
    allDay: false,
    start: new Date(2024, 7, 16, 8, 0),
    end: new Date(2024, 7, 16, 8, 45),
  },
  {
    title: "Electrophysiology",
    allDay: false,
    start: new Date(2024, 7, 16, 9, 0),
    end: new Date(2024, 7, 16, 9, 45),
  },

  {
    title: "Radiation Oncology",
    allDay: false,
    start: new Date(2024, 7, 16, 11, 0),
    end: new Date(2024, 7, 16, 11, 45),
  },
  {
    title: "Radiation Oncology",
    allDay: false,
    start: new Date(2024, 7, 16, 13, 0),
    end: new Date(2024, 7, 16, 13, 45),
  },
  {
    title: "Surgical Oncology",
    allDay: false,
    start: new Date(2024, 7, 16, 14, 0),
    end: new Date(2024, 7, 16, 14, 45),
  },
];